module.exports = {
  projects: [
    '<rootDir>/libs/utils',
    '<rootDir>/libs/xplat/web/layout',
    '<rootDir>/libs/core',
    '<rootDir>/libs/ui',
    '<rootDir>/libs/xplat/web/bb-workspace',
    '<rootDir>/libs/shared',
    '<rootDir>/apps/emu-compat',
    '<rootDir>/libs/user',
    '<rootDir>/libs/xplat/base/rating',
    '<rootDir>/libs/xplat/web/rating',
    '<rootDir>/libs/games-data',
    '<rootDir>/libs/http',
    '<rootDir>/libs/xplat/core',
    '<rootDir>/libs/xplat/features',
    '<rootDir>/libs/xplat/scss',
    '<rootDir>/libs/xplat/utils',
    '<rootDir>/libs/xplat/web/core',
    '<rootDir>/libs/xplat/web/features',
    '<rootDir>/libs/xplat/web/scss',
    '<rootDir>/libs/xplat/nativescript/scss',
    '<rootDir>/libs/xplat/nativescript/utils',
    '<rootDir>/libs/xplat/nativescript/core',
    '<rootDir>/libs/xplat/nativescript/features',
    '<rootDir>/libs/xplat/base/breakerboxer-state',
  ],
};
